#!/bin/bash
#
#	* File     : natmap_callback_config
#	* Author   : sunowsir
#	* Mail     : sunowsir@163.com
#	* Github   : github.com/sunowsir
#	* Creation : Fri 20 Dec 2024 04:02:21 PM CST


# 教程: https://blog.dibin.eu.org/posts/%E5%9C%A8NAT-1%E5%86%85%E7%BD%91IP%E5%AE%BD%E5%B8%A6%E4%B8%8A%E9%83%A8%E7%BD%B2Web%E6%9C%8D%E5%8A%A1%E5%B9%B6%E4%BD%BF%E7%94%A8Cloudflare%E8%BF%9B%E8%A1%8C%E9%87%8D%E5%AE%9A%E5%90%91/


# global define variables by config from config file


AUTH="$(uci get natmap_callback.cloudflare.AUTH)"
export AUTH
[[ -z "${AUTH}" ]] && exit 127

EMAIL="$(uci get natmap_callback.cloudflare.EMAIL)"
export EMAIL
[[ -z "${EMAIL}" ]] && exit 127

RULE="$(uci get natmap_callback.cloudflare.RULE)"
export RULE
[[ -z "${RULE}" ]] && exit 127

CLOUDFLARE_API_URL="$(uci get natmap_callback.cloudflare.CLOUDFLARE_API_URL)"
export CLOUDFLARE_API_URL
[[ -z "${CLOUDFLARE_API_URL}" ]] && exit 127

ROOT_DOMAIN="$(uci get natmap_callback.cloudflare.ROOT_DOMAIN)"
export ROOT_DOMAIN
[[ -z "${ROOT_DOMAIN}" ]] && exit 127

REDIRECT_SUBDOMAIN="$(uci get natmap_callback.cloudflare.REDIRECT_SUBDOMAIN)"
export REDIRECT_SUBDOMAIN
[[ -z "${REDIRECT_SUBDOMAIN}" ]] && exit 127

RETRY_NUM="$(uci get natmap_callback.cloudflare.RETRY_NUM)"
export RETRY_NUM
[[ -z "${RETRY_NUM}" ]] && RETRY_NUM=3

SENDKEY="$(uci get natmap_callback.cloudflare.SENDKEY)"
export SENDKEY

LOGS_SAVE_TIMES="$(uci get natmap_callback.cloudflare.LOGS_SAVE_TIMES)"
export LOGS_SAVE_TIMES
[[ -z "${LOGS_SAVE_TIMES}" ]] && LOGS_SAVE_TIMES=86400

LOGS_SAVE_DIR="$(uci get natmap_callback.cloudflare.LOGS_SAVE_DIR)"
export LOGS_SAVE_DIR
[[ -z "${LOGS_SAVE_DIR}" ]] && LOGS_SAVE_DIR='/var/log/'

LOGS_FILENAME="$(uci get natmap_callback.cloudflare.LOGS_FILENAME)"
export LOGS_FILENAME
[[ -z "${LOGS_FILENAME}" ]] && LOGS_FILENAME='natmap_callback.log'

STATUS_CODE="$(uci get natmap_callback.cloudflare.STATUS_CODE)"
export STATUS_CODE
[[ -z "${STATUS_CODE}" ]] && STATUS_CODE=308


# global export variables


export REDIRECT_DOMAIN="${REDIRECT_SUBDOMAIN}.${ROOT_DOMAIN}"

export LOG_FILE="${LOGS_SAVE_DIR}/${LOGS_FILENAME}"

export FILE_IDLE="$(( $(date '+%s') - $(date -r "${LOG_FILE}" '+%s' 2>/dev/null || echo '0') ))"

export NATMAP_RUNNING_FILE="/var/run/natmap/*.json"

export TMP_DIR="/tmp"

export LOCK_FILE="${TMP_DIR}/.openwrt.natmap.callback.script.lock"

export WORK_SH_FILE="natmap_callback_main"

export CURL_CONN_TIMEOUT=300

export WAIT_TIMEOUT=30
