#!/bin/bash
#
#       * File     : natmap_callback
#       * Author   : sunowsir (rebuild with jshn)
#       * Mail     : sunowsir@163.com
#       * Github   : github.com/sunowsir

WORK_DIR="$(dirname "$(readlink -f "${0}")")"
source "${WORK_DIR}/natmap_callback_config"

mkdir -p "${LOGS_SAVE_DIR}"
[[ ! -f "${LOG_FILE}" ]] && touch "${LOG_FILE}"

# 超过日志保存时长则先删除文件
[[ ${FILE_IDLE} -gt ${LOGS_SAVE_TIMES} ]] && \
    rm -rf "${LOG_FILE}"

flock "${LOCK_FILE}" "${WORK_DIR}"/"${WORK_SH_FILE}" "${@}" >> "${LOG_FILE}" 
